query getItems {
    items {
        id
        title
        description
        image
        largeImage
        price
        source
        category {
            name
            id
        }
    }
}
